### ISSUE TITLE
Trait for async Thrift codec

### ISSUE THREAD

**Issue by ii64** [cloudwego/volo#121]
### Crates

volo-thrift

### Motivation

Extending the Thrift (Apache) Compact protocol support for codec. Currently `volo_thrift::message_wrapper::ThriftMessage<M>` method `decode_async` only accept concrete `&mut TAsyncBinaryProtocol<R>` causing the following compile error:

```
error[E0308]: mismatched types
   --> volo/volo-thrift/src/codec/default/thrift.rs:174:62
    |
174 |                 let msg = ThriftMessage::<Msg>::decode_async(&mut p, cx).await?;
    |                           ---------------------------------- ^^^^^^ expected struct `TAsyncBinaryProtocol`, found struct `TAsyncCompactProtocol`
    |                           |
    |                           arguments to this function are incorrect
    |
    = note: expected mutable reference `&mut TAsyncBinaryProtocol<_>`
               found mutable reference `&mut TAsyncCompactProtocol<&mut volo::util::buf_reader::BufReader<R>>`
note: associated function defined here
   --> volo/volo-thrift/src/message_wrapper.rs:185:25
    |
185 |     pub(crate) async fn decode_async<Cx: ThriftContext + Send, R>(
    |                         ^^^^^^^^^^^^
186 |         protocol: &mut TAsyncBinaryProtocol<R>,
    |         --------------------------------------
```

### Proposal

Trait for async codec, use GAT just like `TInputProtocol` and `TOutputProtocol` are implemented.

### Alternatives

None, RFC?

**Comment by PureWhiteWu** [comment]
I think this makes sense, let's create a TAsyncInputProtocol and TAsyncOutputProtocol instead of rely on TAsyncBinaryProtocol directly.

**Comment by ii64** [comment]
There's blocker, `async_fn_in_trait` is in Nightly - Is this alright?

**Comment by PureWhiteWu** [comment]
We can use `async_trait` crate now.

**Comment by ii64** [comment]
Follow up for this feature, opened 2 PRs:
- https://github.com/cloudwego/pilota/pull/83
- https://github.com/cloudwego/volo/pull/123

**Comment by ii64** [comment]
To be clear, these PRs are only implements `TAsyncInputProtocol` in favor of `pilota::thrift::Message` trait that only support async decode (the `decode_async`).

**Comment by PureWhiteWu** [comment]
你好，你加入了 Volo 飞书群了嘛？

**Comment by ii64** [comment]
> 你好，你加入了 Volo 飞书群了嘛？

你好， 我沒有。飞书需要+86电话号码前缀

**Comment by PureWhiteWu** [comment]
> 你好， 我沒有。飞书需要+86电话号码前缀

好的，你可以试试看注册 [larksuite](https://www.larksuite.com/zh_cn/)，然后加入这个群～
你为 Volo 贡献了多次代码，质量也很高，想问一下你有意愿加入 CloudWeGo 组织成为 Committer 嘛？

**Comment by ii64** [comment]
> 好的，你可以试试看注册 [larksuite](https://www.larksuite.com/zh_cn/)，然后加入这个群～

我加入不了群，好像 Volo 链接不好用。
Link: https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=b34v5470-8e4d-4c7d-bf50-8b2917af026b

<details>
<summary>Demo</summary>

![gifcast_230206011405](https://user-images.githubusercontent.com/26342994/216842269-6a0e16c3-c954-4334-9891-5eb438924ace.gif)
</details>

> 你为 Volo 贡献了多次代码，质量也很高，想问一下你有意愿加入 CloudWeGo 组织成为 Committer 嘛？

好呀

**Comment by PureWhiteWu** [comment]
![image](https://user-images.githubusercontent.com/3314335/216875209-b3f4c288-d884-45fd-8cd1-25d9a74b693e.png)
你好，你可能需要先点击这个，注册一个 个人账户 ，然后再试试看？

**Comment by ii64** [comment]
你好，它使用了！謝謝

**Comment by PureWhiteWu** [comment]
https://github.com/cloudwego/community/issues/10 你好，你要不按照这个 issue 的格式，在 community 上提交一个新的 issue？
