### ISSUE TITLE
我需要rpc 四种请求模式的示例 比如服务端流模式

### ISSUE THREAD

**Issue by Fan-sir** [cloudwego/volo#152]
我需要rpc 四种请求模式的示例 比如服务端流模式

Crates
volo-grpc

Motivation
没有在https://www.cloudwego.io/zh/docs/volo/volo-grpc/getting-started/ 中看到相关示例

Proposal
在开源群里得到了答复：https://github.com/cloudwego/volo/tree/main/examples/src

**Comment by PureWhiteWu** [comment]
感觉我们可以把 examples 加入到 README 里面告知大家，getting-started 还是不希望做太复杂。
