### ISSUE TITLE
how to add custom field to S in volo-rust

### ISSUE THREAD

**Issue by captainjack0x7C8** [cloudwego/volo#168]
Hi，i need to call redis or remote service at fn in struct S.
How to add redis or thrift clients to struct S as struct field, so that i can touch them by '&self'.

**Comment by LYF1999** [comment]
Which struct `S` do you mention?
if you are writing a Server, you can just 
```rust
struct S {
  redis: Redis,
}

impl xxxService for S {
    fn xxx_method(&self, req: xxxReq) -> Result<xxxResponse> {
       // call redis in here
  }
}
```

**Comment by captainjack0x7C8** [comment]
> Which struct `S` do you mention? if you are writing a Server, you can just
> 
> ```rust
> struct S {
>   redis: Redis,
> }
> 
> impl xxxService for S {
>     fn xxx_method(&self, req: xxxReq) -> Result<xxxResponse> {
>        // call redis in here
>   }
> }
> ```

thanks, i was misled by others before
