### ISSUE TITLE
grpc 的调用能像anyhow::Result一样支持任意错误的抛出吗？

### ISSUE THREAD

**Issue by xxaier** [cloudwego/volo#211]
我觉得

`Pin<Box<(dyn Future<Output = Result<volo_grpc::Response<QOut>, Status>`

可以改为

`Pin<Box<(dyn Future<Output = Result<volo_grpc::Response<QOut>, Into<Status>>`

然后 为anyhow::Error 实现 Into<Status>

最后，就可以这么用
` async fn q(&self, req: Request<QIn>) -> Result<Response<QOut>, anyhow::Error> {`

可以作为一个单独的特性，选择性启用

**Comment by PureWhiteWu** [comment]
感觉这样好像更灵活，也不会有 break change？cc @Millione

**Comment by xxaier** [comment]
话说你们平时怎么调试？我想做这个修改，我在外面有一个自己的项目，我以前一直用类似 `volo = {path="/Users/z/git/volo/volo"}`这样就可以让 项目用本地的库了，然后我就可以魔改源码，但是 volo 这么搞不行，会报错

**Comment by Millione** [comment]
> async fn q(&self, req: Request<QIn>) -> Result<Response<QOut>, anyhow::Error> {

@xxaier 我觉得接口可以不用改动，给anyhow::Error实现一下Into就好了，用户返回的时候自己`?`转换一下就好了

> 但是 volo 这么搞不行，会报错

还要把volo相关的crate都改成本地，用grpc就是volo、volo-grpc、volo-build，用thrift就把volo-grpc换成volo-thrift

**Comment by Millione** [comment]
现在只给BoxError实现了Into，理论上也是支持任意错误的抛出的，但最好还是能按照grpc规范来给出有效的错误信息和状态码

**Comment by Millione** [comment]
Close due to resolved. Feel free to reopen if further discuss needed.
