### ISSUE TITLE
cannot find macro `izip` in this scope

### ISSUE THREAD

**Issue by xxaier** [cloudwego/volo#216]
我更新依赖到0.6,报错截图如下

![image](https://github.com/cloudwego/volo/assets/130831741/ce3cca3f-2d21-4919-9cc6-456a36812f3a)

**Comment by Millione** [comment]
执行 `cargo tree | grep itertools` 看看依赖的版本呢？

**Comment by PureWhiteWu** [comment]
你好，解决了么？ @xxaier

**Comment by wacdev** [comment]
见截图如下，没截图
![image](https://github.com/cloudwego/volo/assets/127726508/cc6d718d-26b9-461f-96b7-334af6f12a3f)

**Comment by PureWhiteWu** [comment]
你执行 cargo update 试试？

**Comment by wacdev** [comment]
如图，一样的错误
![image](https://github.com/cloudwego/volo/assets/127726508/99fac15f-64ae-4011-a502-3d5ec635834f)

https://github.com/xxai-art/clip-runtime/

代码在这里
这个目录 clip-runtime/rust/clip_search_txt

**Comment by PureWhiteWu** [comment]
我刚尝试了一下，拉下来之后，手动去 Cargo.toml 中把 volo-build 改为 0.6 是可以编译过的。
你不要用 cargo upgrade，直接手动改 Cargo.toml 然后 cargo update 编译试试？

**Comment by wacdev** [comment]
我找到原因了，删除target重新编译就可以了
