### ISSUE TITLE
eProsima Serialization

### ISSUE THREAD

**Issue by marvin-hansen** [cloudwego/volo#261]
## Feature Request

Please assess eProsima as a faster alternative to proto. 

### Crates

Volo 

### Motivation

QPS matters a lot and serialization and deserialization contributes a lot to the overall performance. As it seems eProsima is quite a bit faster than proto and thrift while improving latency. 

Windows and Linux seems to be supported out of the box but Mac support is unclear from the documentation. 

https://www.eprosima.com/index.php/resources-all/performance/apache-thrift-vs-protocol-buffers-vs-fast-buffers

https://www.eprosima.com/index.php/resources-all/performance/eprosima-fast-dds-performance

### Proposal

There is a comprehensive C/C++ API that might need to get wrapped in Rust via unsafe. 

https://www.eprosima.com/docs/fast-buffers/0.3.0/html/index.html

https://www.eprosima.com/index.php/products-all/tools/eprosima-fast-buffers

As I said, the actual question here is to start an assessment if it's worth integrating eprosima as a third option for better performance. 

Maybe it's worth starting with a simple experiment to figure out if the performance gains are real?

**Comment by PureWhiteWu** [comment]
Hi, thanks for this feature request!
I'm not familiar with eProsima and seems there's no detailed description about why it's performance is better than thrift and proto.
In our tests, the performance of our optimized thrift is better than proto, and the codec part costs a little in the application. If you have time, could you please help us to compare the performance between volo-thrift and eProsima?

**Comment by marvin-hansen** [comment]
I tried to install the volo CLI on MacOS 14 / M1 but got 99 errors.  Don't have the time to debug this.

**Comment by PureWhiteWu** [comment]
> I tried to install the volo CLI on MacOS 14 / M1 but got 99 errors. Don't have the time to debug this.

Hello, did you switch to the nightly channel using `rustup default nightly` first?
