### ISSUE TITLE
按照文档上的快速开始操作 无法生成模板代码

### ISSUE THREAD

**Issue by 1369521908** [cloudwego/volo#300]
## Bug Report

按照文档上的快速开始操作 无法生成模板代码
是不是我的环境有问题?

### Version

![image](https://github.com/cloudwego/volo/assets/32727597/8b5bb597-8f87-40e1-8684-a8371e2e285e)

### Platform

![image](https://github.com/cloudwego/volo/assets/32727597/9ba108e2-e9ad-44c6-9bbc-1b9bac2cc39f)

### Description

![image](https://github.com/cloudwego/volo/assets/32727597/66837372-4673-41a8-a4eb-24e8b8e2ac96)

**Comment by PureWhiteWu** [comment]
你好 
![image](https://github.com/cloudwego/volo/assets/3314335/e5b8d2eb-f33e-4b81-914c-be1923da32d6)
这里改成 idl\volo_example.proto 试试呢？

**Comment by 1369521908** [comment]
![image](https://github.com/cloudwego/volo/assets/32727597/a5a50320-416e-4faf-8f1e-f90c613436f7)
还是不行

**Comment by 1369521908** [comment]
是不是我没安装protoc的原因?
https://github.com/protocolbuffers/protobuf/releases/tag/v25.1

**Comment by Millione** [comment]
应该是文件路径没写对的原因，导致没有权限访问

**Comment by PureWhiteWu** [comment]
把 --includes=idl 先去掉再试试看呢？

**Comment by 1369521908** [comment]
![image](https://github.com/cloudwego/volo/assets/32727597/980b0eb4-76b5-4598-baa6-b2e6b4ee81c5)

**Comment by 1369521908** [comment]
![image](https://github.com/cloudwego/volo/assets/32727597/f42cb134-cab7-4bbd-a091-15ef5e8e22b8)

**Comment by 1369521908** [comment]
> 应该是文件路径没写对的原因，导致没有权限访问

如果没写对 会返回找不到文件
![image](https://github.com/cloudwego/volo/assets/32727597/3b4a4758-3f98-4d6c-82aa-cdb3c321b889)

**Comment by 1369521908** [comment]
> 把 --includes=idl 先去掉再试试看呢？

![image](https://github.com/cloudwego/volo/assets/32727597/d838254d-7071-483e-b5d0-b5b35db8e5a1)

**Comment by PureWhiteWu** [comment]
你能尝试使用 WSL 再试试看么？我们没有 Windows 系统环境，也不太能复现这个问题。
或者你先试试看创建一个 thrift 的 idl？

**Comment by 1369521908** [comment]
> 你能尝试使用 WSL 再试试看么？我们没有 Windows 系统环境，也不太能复现这个问题。 或者你先试试看创建一个 thrift 的 idl？

行 后面有空我试试

**Comment by 1369521908** [comment]
> 你能尝试使用 WSL 再试试看么？我们没有 Windows 系统环境，也不太能复现这个问题。 或者你先试试看创建一个 thrift 的 idl？

thrift 的可以生成成功
![image](https://github.com/cloudwego/volo/assets/32727597/3c6d97ac-3800-43d5-952d-09cc723b30b8)
![image](https://github.com/cloudwego/volo/assets/32727597/e47487d0-595c-44d9-9b47-a429072e02c9)

**Comment by 1369521908** [comment]
> 你能尝试使用 WSL 再试试看么？我们没有 Windows 系统环境，也不太能复现这个问题。 或者你先试试看创建一个 thrift 的 idl？

wsl被我干掉了[doge]
![23464E1E](https://github.com/cloudwego/volo/assets/32727597/79b34ebf-9810-48dd-85bb-8491caef1b3f)

**Comment by PureWhiteWu** [comment]
好的，我猜测是 windows 把 idl 当作盘符了。。。
你试试看，改成 --includes=.\idl 看看是否可行？

**Comment by 1369521908** [comment]
> 好的，我猜测是 windows 把 idl 当作盘符了。。。 你试试看，改成 --includes=.\idl 看看是否可行？

![image](https://github.com/cloudwego/volo/assets/32727597/e5eb3587-9f72-4cf3-aa6a-c82c81f5cde2)

**Comment by rogerogers** [comment]
https://github.com/cloudwego/volo/blob/d155871bd99afe187ebfce416ff7e46b4416a77d/volo-build/src/model.rs#L80 这个方法在 windows 上没法判断文件夹貌似。

**Comment by PureWhiteWu** [comment]
> https://github.com/cloudwego/volo/blob/d155871bd99afe187ebfce416ff7e46b4416a77d/volo-build/src/model.rs#L80
> 
> 这个方法在 windows 上没法判断文件夹貌似。

感谢，感觉很有可能是这个导致的，你有兴趣提个 pr 进行修复嘛？

**Comment by rogerogers** [comment]
> > https://github.com/cloudwego/volo/blob/d155871bd99afe187ebfce416ff7e46b4416a77d/volo-build/src/model.rs#L80
> > 
> > 这个方法在 windows 上没法判断文件夹貌似。
> 
> 感谢，感觉很有可能是这个导致的，你有兴趣提个 pr 进行修复嘛？

我试下，我写 rust 不多。

**Comment by Conan520** [comment]
> > > https://github.com/cloudwego/volo/blob/d155871bd99afe187ebfce416ff7e46b4416a77d/volo-build/src/model.rs#L80
> > > 
> > > 这个方法在 windows 上没法判断文件夹貌似。
> > 
> > 
> > 感谢，感觉很有可能是这个导致的，你有兴趣提个 pr 进行修复嘛？
> 
> 我试下，我写 rust 不多。

![image](https://github.com/cloudwego/volo/assets/66357304/aff37703-a5df-45e8-ae22-3cbd44b9da69)
