### ISSUE TITLE
connection closed because of a broken pipe

### ISSUE THREAD

**Issue by 5waker** [cloudwego/volo#330]
### Version

<img width="254" alt="图片" src="https://github.com/cloudwego/volo/assets/56286666/f79d0392-e8e0-444e-b0fd-d3f77a83ac06">

### Platform
linux

### Crates

cli demo default

### Description

我使用volo作为client调用go服务，go服务确保可用，调用已经打到server端，然后server出现context cancel，client出现connection closed because of a broken pipe
<img width="1744" alt="图片" src="https://github.com/cloudwego/volo/assets/56286666/bd5990e3-2671-454f-b5c3-b076b48fe868">

<img width="1475" alt="图片" src="https://github.com/cloudwego/volo/assets/56286666/a4ae7884-a6c7-4f2a-9f56-129db944e3f9">

服务端代码是参照官网文档写的
<img width="1442" alt="图片" src="https://github.com/cloudwego/volo/assets/56286666/dd68681b-cba8-411e-8c2c-2fc2e5d3675b">

**Comment by PureWhiteWu** [comment]
看起来是由于 Server 端 context cancel 导致的连接被关闭，导致的 client 报错 broken pipe？

**Comment by 5waker** [comment]
> ## Bug Report
> ### Version
> <img alt="图片" width="254" src="https://private-user-images.githubusercontent.com/56286666/297746360-f79d0392-e8e0-444e-b0fd-d3f77a83ac06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODY1MTcsIm5iZiI6MTcwNTU4NjIxNywicGF0aCI6Ii81NjI4NjY2Ni8yOTc3NDYzNjAtZjc5ZDAzOTItZThlMC00NDRlLWIwZmQtZDNmNzdhODNhYzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwMDRlMmU3NmEzZmExMzdiNDNkNDYwYzVkZDE2NWI5YWIyMjBhNmQ0MmM4ZDM2NmM5NGJmOWRkNzZlNTUyY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TJWtyrCHahk5GIyuEXEJxykMbTFZFyU9ad46oRMVg68">
> ### Platform
> 
> linux
> ### Crates
> 
> cli demo default
> ### Description
> 
> 我使用volo作为client调用go服务，go服务确保可用，调用已经打到server端，然后server出现context cancel，client出现connection closed because of a broken pipe <img alt="图片" width="1744" src="https://private-user-images.githubusercontent.com/56286666/297750969-bd5990e3-2671-454f-b5c3-b076b48fe868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODY1MTcsIm5iZiI6MTcwNTU4NjIxNywicGF0aCI6Ii81NjI4NjY2Ni8yOTc3NTA5NjktYmQ1OTkwZTMtMjY3MS00NTRmLWI1YzMtYjA3NmI0OGZlODY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMTk0YjZiMzkwZTAwZGU1NjBjYmJiZGQyNGMxZDNmODg0Y2NlNzRmNTBjNjRhMGNmNGQyZmJlODNkODdjZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fd-FTS4JJG1ZxoKjW-aIJayPIXELUU3xtLrJQvL9k7I">
> <img alt="图片" width="1475" src="https://private-user-images.githubusercontent.com/56286666/297749989-a4ae7884-a6c7-4f2a-9f56-129db944e3f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODY1MTcsIm5iZiI6MTcwNTU4NjIxNywicGF0aCI6Ii81NjI4NjY2Ni8yOTc3NDk5ODktYTRhZTc4ODQtYTZjNy00ZjJhLTlmNTYtMTI5ZGI5NDRlM2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4YzViNGE5NzNiYjAwMGQzNDBkNzljMWE1NGNkZmIzMDUwNDFhNmM1YzNlNTMwZmFmOGU3MzBjOTRkZjc2ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IeICSkfH0GJeNFuR7qsCyxxqVoYR5IsbTT4OfruuxuU">
> 
> 客户端代码是参照官网文档写的 <img alt="图片" width="1442" src="https://private-user-images.githubusercontent.com/56286666/297752299-dd68681b-cba8-411e-8c2c-2fc2e5d3675b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODY1MTcsIm5iZiI6MTcwNTU4NjIxNywicGF0aCI6Ii81NjI4NjY2Ni8yOTc3NTIyOTktZGQ2ODY4MWItY2JhOC00MTFlLThjMmMtMmZjMmU1ZDM2NzViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZWYzN2UxNmM4YmRjYTY2OGUzYjUwZDAxNzdkZjNhYjgwMjI0MGVlMzI1Yjg3YjY0YzgwZWNkOGJjZTI0ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B8-aG4WWYetfMjeDYooqI4DVimuuhvaEiBvIxcRbJvY">

**Comment by PureWhiteWu** [comment]
如果是用的 gRPC 的话，试试看 volo-grpc 0.8 行不行呢？应该直接在 Cargo.toml 里面指定一下版本就行

**Comment by 5waker** [comment]
> 如果是用的 gRPC 的话，试试看 volo-grpc 0.8 行不行呢？应该直接在 Cargo.toml 里面指定一下版本就行

volo-grpc换成0.8，就无法正常编译。我再尝试用volo实现相同功能的server调用试试

**Comment by 5waker** [comment]
> 如果是用的 gRPC 的话，试试看 volo-grpc 0.8 行不行呢？应该直接在 Cargo.toml 里面指定一下版本就行

我尝试了volo作为server是可以正常访问的，但grpcurl可以正常访问就说不通，我尝试debug了下，在server端获取到以下的错误
received an illegal stream id: 1. headers frame: [FrameHeader HEADERS flags=END_STREAM|END_HEADERS stream=1 len=12]

**Comment by 5waker** [comment]
> > 如果是用的 gRPC 的话，试试看 volo-grpc 0.8 行不行呢？应该直接在 Cargo.toml 里面指定一下版本就行
> 
> 我尝试了volo作为server是可以正常访问的，但grpcurl可以正常访问就说不通，我尝试debug了下，在server端获取到以下的错误 received an illegal stream id: 1. headers frame: [FrameHeader HEADERS flags=END_STREAM|END_HEADERS stream=1 len=12]

volo和grpcurl发起请求时都会产生3个frame，但是grpcurl的每个frame的streamid都会递增+2(例如 1,3,5)，volo则没有递增(例如1,1,1)，因此导致报错

**Comment by PureWhiteWu** [comment]
@5waker 太赞了！你有兴趣提个 PR 修复一下这个问题嘛？

**Comment by 5waker** [comment]
> @5waker 太赞了！你有兴趣提个 PR 修复一下这个问题嘛？

可以，但是我还没定位到根因，我用example里的proto同样无法正常调用go服务，看来是普遍的问题
![图片](https://github.com/cloudwego/volo/assets/56286666/17099acb-1d98-4a1b-b39b-8f2eb4f3811c)

**Comment by 5waker** [comment]
> > @5waker 太赞了！你有兴趣提个 PR 修复一下这个问题嘛？
> 
> 可以，但是我还没定位到根因，我用example里的proto同样无法正常调用go服务，看来是普遍的问题 ![图片](https://private-user-images.githubusercontent.com/56286666/298352691-17099acb-1d98-4a1b-b39b-8f2eb4f3811c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MzU0MzgsIm5iZiI6MTcwNTgzNTEzOCwicGF0aCI6Ii81NjI4NjY2Ni8yOTgzNTI2OTEtMTcwOTlhY2ItMWQ5OC00YTFiLWIzOWItOGYyZWI0ZjM4MTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDExMDUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZjYwN2Q3Y2ExODhlMDVlYTU1ZGQwOWQzNWRmZWQ4ZGNjYzg2MGYwYjEyNmU2ODAxNGNhMzc2OTVjM2E1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wo7IW-M_5RAZ5riXo1y-gMyj5hvwLRxFlhMmfaIk2D8)

我尝试了一些方案，如升级hyper，修改set_nodelay(false) ，这里会缓冲数据发送两次而不是三次，在调试状态下偶尔能拿到数据（并不算正向修复）。均未获得成功。stream id 始终为1，并不增长。
```
2024-01-21T10:58:27.827937Z DEBUG h2::client: binding client connection
2024-01-21T10:58:27.828017Z DEBUG h2::client: client connection bound
2024-01-21T10:58:27.828076Z DEBUG h2::codec::framed_write: send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 65535, max_frame_size: 16384 }
2024-01-21T10:58:27.828605Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=Settings { flags: (0x0), max_frame_size: 16384 }
2024-01-21T10:58:27.828685Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Settings { flags: (0x1: ACK) }
2024-01-21T10:58:27.828778Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
2024-01-21T10:58:27.828925Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Data { stream_id: StreamId(1) }
2024-01-21T10:58:27.828979Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
2024-01-21T10:58:27.829477Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=Settings { flags: (0x1: ACK) }
2024-01-21T10:58:27.829540Z DEBUG Connection{peer=Client}: h2::proto::settings: received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 65535, max_frame_size: 16384 }
2024-01-21T10:58:27.829586Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=WindowUpdate { stream_id: StreamId(0), size_increment: 8 }
2024-01-21T10:58:27.829656Z DEBUG Connection{peer=Client}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
2024-01-21T10:58:27.829707Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
2024-01-21T10:58:27.830017Z ERROR client: Status { code: Unknown, message: "connection error", source: Some(hyper::Error(Io, Custom { kind: BrokenPipe, error: "connection closed because of a broken pipe" })) }
```

@PureWhiteWu 我想咨询下之前版本中volo有调用过标准的go grpc服务嘛？ 因为我看到这个校验在grpc中加的很早 https://github.com/grpc/grpc/issues/957 如果之前能成功调用说明是引入bug，这样能通过查询commit来缩小排查范围。

**Comment by Millione** [comment]
@5waker 0.8.0版本是好的，估计是在这里 https://github.com/cloudwego/volo/pull/285 引入的问题
