### ISSUE TITLE
volocli 生成的代码中的async-trait依赖是否可去除？

### ISSUE THREAD

**Issue by 5waker** [cloudwego/volo#331]
我发现即使删除volo cli 生成的async-trait代码也可以正常编译运行，请问此处是否可以去除？

**Comment by PureWhiteWu** [comment]
你好，可以的，有兴趣来提个 PR 嘛？

**Comment by 5waker** [comment]
> 你好，可以的，有兴趣来提个 PR 嘛？

可以，我试试

**Comment by my-vegetable-has-exploded** [comment]
template中的模板里面，还有cargo toml中的async-trait.workspace，这个应该也可以清一下

**Comment by 5waker** [comment]
#332

**Comment by 5waker** [comment]
#332
