### ISSUE TITLE
[Question] Update IDL 

### ISSUE THREAD

**Issue by YxYL6125** [cloudwego/volo#351]
What I want to know is what command should I execute to update the server side template code after I have modified the idl file

**Comment by PureWhiteWu** [comment]
Hello, if you want to update the idl version, you can use `volo idl update`.

However, the template cannot be updated (the `lib.rs` file), you need to manually add new functions you need.

**Comment by YxYL6125** [comment]
Ok, tks~ By the way what does `volo idl update` command do. I found out that just the `volo.yaml` file had changed,

**Comment by PureWhiteWu** [comment]
Yes, the command only update the git revision of idl, and when you execute `cargo check` or `cargo build`, the code will be re-generated.

**Comment by YxYL6125** [comment]
Ok～
