### ISSUE TITLE
服务端函数增加获取客户端IP地址途径

### ISSUE THREAD

**Issue by JasonHonor** [cloudwego/volo#373]
### Crates

volo-thrift v0.9.2

### Motivation

示例代码在Server端生成的服务函数get_item函数，需要增加客户端IP地址信息。

### Proposal

用于关注客户端地址的业务应用，如：接口的IP白名单等。

**Comment by PureWhiteWu** [comment]
可以增加一个中间件，在中间件中通过 cx.rpc_info().caller().address() 获取试试？

**Comment by JasonHonor** [comment]
多谢，将示例的LogService中的cx改为 Send+'static+ volo::context::Context, 能够调用cx.rpc_info().caller().address()，本机服务端和本机客户端调试，输出的caller().address() 是None。
