### ISSUE TITLE
在跑volo样例compression的时候发现跑不起来

### ISSUE THREAD

**Issue by SuperD-dd** [cloudwego/volo#406]
### Description
![111](https://github.com/cloudwego/volo/assets/84621173/b8e6ef15-369b-4576-8c1f-3470c117f956)
运行样例compression的时候手敲发现没有跑起来，发现是Bin包作者漏了一个s

**Comment by PureWhiteWu** [comment]
感谢指出，是否有兴趣提个 PR 修复一下呀？

**Comment by SuperD-dd** [comment]
> 感谢指出，是否有兴趣提个 PR 修复一下呀？

嗯嗯好的，https://github.com/cloudwego/volo/pull/407
