### ISSUE TITLE
基于 UrlParams 的使用场景，对其进行重命名的建议。

### ISSUE THREAD

**Issue by liuxin231** [cloudwego/volo#415]
### Crates

volo-http

### Motivation

增强可用性和可读性。

### Proposal

根据提交的UrlParams参数提取方式进行测试后发现只会提取Path内的参数，如 axum 框架内 /api/:id 的使用方式，并不会提取url问号后的参数，该参数命名是否可以参考其他框架的命名，也为后续的其他参数提取留出空间。

### Alternatives

修改 UrlParams 为 PathParams 或 Path.

**Comment by wfly1998** [comment]
`PathParams` 确实会比 `UrlParams` 描述更准确一些，我稍后提个 PR 修改一下。

不过你提到的 “问号后的参数” 这个其实叫 query，在 `volo-http` 中可以用 `Query` 来提取。

**Comment by liuxin231** [comment]
了解，不知道这个修改我是否可以进行，想要参与该框架的贡献。

**Comment by wfly1998** [comment]
可以的，不过为了避免这种名字修改导致的 break change，建议修改后再保留一个 alias，比如

```diff
--- pub struct UrlParams<T> { ... }
+++ pub struct PathParams<T> { ... }
+++
+++ pub type UrlParams<T> = PathParams<T>;
```

在后续的版本中，我可以为 `UrlParams` 添加 `deprecated` 标记。

**Comment by liuxin231** [comment]
了解，稍后提交。
