### ISSUE TITLE
最新版本编译异常

### ISSUE THREAD

**Issue by GreenAppleOne** [cloudwego/volo#492]
23  | pub fn missing_field<'de, V, E>(field: &'static str) -> Result<V, E>
    |        ------------- required by a bound in this function
24  | where
25  |     V: Deserialize<'de>,
    |        ^^^^^^^^^^^^^^^^ required by this bound in `missing_field`
    = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `volo-build` (lib) due to 30 previous errors

**Comment by GreenAppleOne** [comment]
error[E0277]: the trait bound `volo::FastStr: Deserialize<'_>` is not satisfied

**Comment by yukiiiteru** [comment]
有什么其他的上下文吗，看起来可能是有什么 crate 的版本不一致造成的，因为我们这边的 CI 检查都是可以通过的

**Comment by GreenAppleOne** [comment]
![image](https://github.com/user-attachments/assets/45ba09f9-b781-4a9a-b21a-5671dfd983a1)

**Comment by PureWhiteWu** [comment]
感谢提出，已经在最新版本中修复了，方便的话更新最新版再试试看？
