### ISSUE TITLE
Support auto generate default impl code in lib.rs in volo-cli init command / 使用 volo-cli init 时支持在 lib.rs 中自动生成一个默认实现

### ISSUE THREAD

**Issue by PureWhiteWu** [cloudwego/volo#5]
### Crates

volo-cli

### Motivation

Currently, we only generate an empty `impl` block for users, and they need to fill in this to get compiled.

It's better to generate a default impl for them when they call init command, such as a simple `Ok(Default::default())`.

目前 volo-cli 的 init 命令，只会生成一个空的`impl`代码块，用户必须补足这块才能编译通过。

如果我们能够在 init 时自动为用户生成一个默认实现，例如`Ok(Default::default())`会更好。

### Proposal

First, we need to get the last service defined and its functions from the thrift or protobuf AST.

Then, we need to generate a struct for it, and provide a default impl for each function.

首先，我们需要从 thrift 或者 protobuf 的 AST 中获得用户定义的最后一个 service。

其次，我们需要为这个 service 的每一个方法生成一个默认的实现。

### Question

Do we need to use another template engine instead of the built-in println macro?

我们是否需要更换一个更强大的模板引擎？

**Comment by my-vegetable-has-exploded** [comment]
“default impl for each function”是不是主要对service每个函数都返回一个返回类型的default？

**Comment by PureWhiteWu** [comment]
是的，目前是这么想的；当然，如果进一步的话，可以考虑通过 plugin 等方式看看能否自定义生成的默认代码。

**Comment by my-vegetable-has-exploded** [comment]
> 是的，目前是这么想的；当然，如果进一步的话，可以考虑通过 plugin 等方式看看能否自定义生成的默认代码。

我看了一下，proto或者thrift是在build时候（template已经转成target file，lib.rs已经生成），感觉要实现这个功能的话，需要将build移动到init过程里面去，以及函数部分需要通过pilota获取吗？。
另外plugin具体是指那个部分呢？ 没有明白。
感谢，我再看一点之后看看能不能try一try

**Comment by PureWhiteWu** [comment]
是的，是需要在 init 里面接入 pilota-build 获取到对应的 IR 信息了。
plugin 指的是 pilota-build 的 plugin。
你在开发者群里嘛？

**Comment by my-vegetable-has-exploded** [comment]
> 是的，是需要在 init 里面接入 pilota-build 获取到对应的 IR 信息了。

ok，我再看看，谢谢。

我加了飞书用户群。

**Comment by PureWhiteWu** [comment]
你飞书群 id 是哪个呀？这个任务可能得需要一些来自 @lyf1999 的帮助

**Comment by my-vegetable-has-exploded** [comment]
我的飞书名称是王毅

> 这个任务可能得需要一些来自 @LYF1999 的帮助

ok，有问题我就去请教下。

**Comment by PureWhiteWu** [comment]
Hello，你好，我看字节校园的那个账号被关闭了，你有自己的飞书个人账号嘛？

**Comment by my-vegetable-has-exploded** [comment]
> Hello，你好，我看字节校园的那个账号被关闭了，你有自己的飞书个人账号嘛？

有的，我个人账号也加了volo用户群，字节校园的号上个月月底被停了（

**Comment by my-vegetable-has-exploded** [comment]
Done

**Comment by PureWhiteWu** [comment]
@my-vegetable-has-exploded 感谢你的贡献～

**Comment by Millione** [comment]
@my-vegetable-has-exploded 在新发版的volo-cli 0.6.0中带上了这个实现，在执行volo init初始化项目的时候会失败报错，应该和这行有关系，https://github.com/cloudwego/volo/blob/main/volo-cli/src/init.rs#L120

**Comment by my-vegetable-has-exploded** [comment]
> @my-vegetable-has-exploded 在新发版的volo-cli 0.6.0中带上了这个实现，在执行volo init初始化项目的时候会失败报错，应该和这行有关系，https://github.com/cloudwego/volo/blob/main/volo-cli/src/init.rs#L120

![图片](https://github.com/cloudwego/volo/assets/48236141/b4f58a95-cdfe-4996-bd01-079b0b811349)

我之前看volo文档, 觉得这部分需要用户去命令行前export OUT_DIR="xxx"去设置一下, 所以就没有处理。

https://github.com/cloudwego/volo/blob/7d362065b004b41db99d50293b2d05437659ada6/volo-build/src/util.rs#L15 

或许我们可以在这里添加一个默认路径？

**Comment by Millione** [comment]
@my-vegetable-has-exploded  https://github.com/cloudwego/volo/pull/215 目前是这样修复的，OUT_DIR这个环境变量是跑cargo时cargo自动注入的

**Comment by my-vegetable-has-exploded** [comment]
> OUT_DIR这个环境变量是跑cargo时cargo自动注入的

没有理解诶， 这个是在哪个部分注入的呀？ 我之前一直以为是user定义的。

**Comment by my-vegetable-has-exploded** [comment]
非常不好意思导致了这个问题，当时没有多想想问问搞清楚。

**Comment by Millione** [comment]
没事的～，没问题的话我就关issue了
