### ISSUE TITLE
支持自定义 ThriftBackend 代码生成

### ISSUE THREAD

**Issue by boringplay** [cloudwego/volo#500]
### Crates
volo_build

### Motivation
给 struct 增加一些自定义生成代码，例如增加一些方法或者实现

### Proposal

volo_build 上支持 ThriftBackend 插件

**Comment by PureWhiteWu** [comment]
你好，可以参考下 https://www.cloudwego.io/docs/volo/pilota/#how-to-write-a-plugin 这个文档，可以通过这个方式来增加一些自定义的生成代码

**Comment by boringplay** [comment]
看例子是只能增加 derive么？是需要自己写宏，然后在宏里面写自定义代码实现？

**Comment by PureWhiteWu** [comment]
不是的，plugin 其实加什么都可以的，不只是 derive

**Comment by boringplay** [comment]
用了一下，`with_adjust_mut` 只能往 struct 前加代码，不能往 struct 后加代码。会出现一些 case。例如

```rs
#[derive(PartialOrd, Hash, Eq, Ord, Debug, Default)]
// 这里是我增加的代码
pub mod xxx {}

#[derive(Clone, PartialEq)]
pub struct SomeStruct {
   // ...
}

```

**Comment by PureWhiteWu** [comment]
@boringplay 如果是加代码，应该用的不是 add_attrs 这个方法？cc @Millione
