### ISSUE TITLE
error: non-defining opaque type use in defining scope

### ISSUE THREAD

**Issue by Ake-w** [cloudwego/volo#68]
### Version

volo v0.2.0

### Platform

Windows 11 64-bit

active toolchain

nightly-x86_64-pc-windows-msvc (overridden by 'D:\volo-example\rust-toolchain.toml')
rustc 1.66.0-nightly (758f19645 2022-10-24)

### Description

run this [example](https://www.cloudwego.io/zh/docs/volo/volo-grpc/getting-started/part_2/ )

```bash
error: non-defining opaque type use in defining scope
   --> C:\Users\xxx\.cargo\registry\src\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\volo-0.2.0\src\loadbalance\random.rs:128:9
    |
128 | /         async {
129 | |             let key = discover.key(endpoint);
130 | |             let weighted_list = match self.router.entry(key) {
131 | |                 Entry::Occupied(e) => e.get().clone(),
...   |
148 | |             })
149 | |         }
    | |_________^ lifetime `'future` is part of concrete type but not used in parameter list of the `impl Trait` type alias
```

**Comment by storyseeker** [comment]
I encountered the same problem, how to solve it?

**Comment by PureWhiteWu** [comment]
This is an issue of the rustc compiler: https://github.com/rust-lang/rust/issues/100013
We are working on this, and will release a new version (perhaps) today.

**Comment by PureWhiteWu** [comment]
Hello, version 0.2.1 is released, and this problem has been fixed.

**Comment by storyseeker** [comment]
> Hello, version 0.2.1 is released, and this problem has been fixed.

It works. Thanks!
