### ISSUE TITLE
Support consistent hash load balance / 支持一致性哈希路由

### ISSUE THREAD

**Issue by PureWhiteWu** [cloudwego/volo#7]
### Crates

volo

### Motivation

Consistent hash load balance is useful and important, we need to support it.

一致性哈希路由是一个很常用也很重要的路由策略，我们需要支持它。

### Proposal

We can refer to the [implementation of Kitex](https://github.com/cloudwego/kitex/blob/develop/pkg/loadbalance/consist.go), which uses the hash ring algorithm.

We can also use red-black tree to optimize the performance.

我们可以参考[`Kitex`的实现](https://github.com/cloudwego/kitex/blob/develop/pkg/loadbalance/consist.go)，并在其基础之上进行优化，如使用红黑树进行在线的更新。

### Alternatives

Is there any other better implementations?

欢迎大家提出更佳的实现方式。

**Comment by my-vegetable-has-exploded** [comment]
Can you assign this issue to me? I have read the code of kitex load balancing part and want to try this issue. In addition, if I encounter some difficulties, how can I communicate with you?
可以把这个issue分配给我吗？我阅读了一下kitex 负载均衡部分的代码，想尝试一下这个issue。另外如果我碰到一些困难，要如何和您沟通呢？

**Comment by PureWhiteWu** [comment]
太赞了！欢迎呀！
如果遇到了问题可以加入 Volo 用户群和我们沟通，也可以直接在这个 issue 下提出，我们都会尽快回复的～

**Comment by my-vegetable-has-exploded** [comment]
我觉得在volo的实现中，负载均衡模块从picker中获取instance [volo layer call](https://github.com/cloudwego/volo/blob/247f658e57f81ada50b14aa4166bec96ada22ef9/volo/src/loadbalance/layer.rs#L87)，没有传入context，但是一致性hash需要从context中获取key信息，我感觉可能需要更改这个picker部分 [InstanceIter](https://github.com/cloudwego/volo/blob/247f658e57f81ada50b14aa4166bec96ada22ef9/volo/src/loadbalance/mod.rs#L20)， 把ctx加入picker的next方法中。
另外一个部分也是关于key，volo中context不像golang一样维护了一个map ，使用 [kitex KeyFunc](https://github.com/cloudwego/kitex/blob/164d3a2a3a01a63a6d6895779917a861f017a800/pkg/loadbalance/consist.go#L57) 这种方式感觉比较难搞。 我看了看brpc实现中，是用户直接传递在hash code的方式，我想直接把这一部分直接放入[RpcInfo](https://github.com/cloudwego/volo/blob/247f658e57f81ada50b14aa4166bec96ada22ef9/volo/src/context.rs#L195)，但是我不清楚是否合理，因为我看volo的示例中callopt是直接嵌入client中的，CLIENT.clone().with_callopt(callopt)，看起来如果调用要修改hash code都需要clone一个client然后重新apply opt（因为我只找到oneshotServer的实现方式，长连接方式代码位置麻烦告诉我一下），感觉存在一些不必要开销。
![image](https://user-images.githubusercontent.com/48236141/229355664-bd2f0df8-c28e-4b08-a066-6c70804027d1.png)

还有就是类似kitex中的实现方式，这个consistBalancer应该是一个单例？（实在是没有在kitex找到用这个模块的示例，也没见kitex提供了选择一致性hash的option）。（设置option来选择balancer实现想后面再考虑。）

因为涉及到对其它模块修改，想听听您的建议。

**Comment by PureWhiteWu** [comment]
非常感谢你提供的信息！

关于第一点，我们内部也有一些讨论，目前的抽象确实无法支持一致性哈希的方便扩展，确实需要重构，这部分 @ethe 可以一起来讨论一下。

关于第二点，Volo 的 context 中有 extension，也有类似 map 的结构，另外也没太明白为什么使用 KeyFunc 这种形式会比较复杂？
我觉得传递 hash code 并且硬编码到 RpcInfo 这种方式比较丑陋而且对用户体验也不好，更像是框架一开始设计时没考虑清楚最后迫不得已开的洞，更好的方式还是使用 KeyFunc，传递给用户 cx 和 req，让用户计算得出对应的 key。

关于第三个问题，consistBalancer 不是单例，预期是每个 Client 初始化一个 consistBalancer，使用方式为由用户初始化并在 NewClient 的时候使用 WithLoadBalancer 直接传入（go 伪代码）：
```go
lb := consist.NewConsistBalancer(keyFunc, ...)
client := xxx.MustNewClient(serviceName, client.WithLoadBalancer(lb))
...
```

PS: Kitex 的 ConsistBalancer 就是我设计实现的，有疑问的话欢迎一起讨论哈～

**Comment by ethe** [comment]
Context 可以在 load balance service 中取到，因此我不能确定一致性哈希路由可以作为 load balance service 实现还是必须扩展 `LoadBalance` trait。

**Comment by my-vegetable-has-exploded** [comment]
> 关于第二点，Volo 的 context 中有 extension，也有类似 map 的结构，另外也没太明白为什么使用 KeyFunc 这种形式会比较复杂？ 我觉得传递 hash code 并且硬编码到 RpcInfo 这种方式比较丑陋而且对用户体验也不好，更像是框架一开始设计时没考虑清楚最后迫不得已开的洞，更好的方式还是使用 KeyFunc，传递给用户 cx 和 req，让用户计算得出对应的 key。
> 
我阅读代码，觉得使用with_opt生成出的client都是oneshot类型的，所以使用call_opt需要每次clone，代码注释中说*it's cheap to clone a `Client`?*， 看代码不是很理解，这个client的clone实现有特别之处吗？我不清楚如果有一致性hash的balancer会不会开销导致clone开销大之类。 然后就是Volo 的 context 的extension，我看类型是TypeMap（不过没有找到如何通过callopt添加extension），使用这种TypeMap怎么实现KeyFunc比较合适呢？

**Comment by PureWhiteWu** [comment]
clone 的话就是一次 Arc 操作，所以是比较 cheap 的，一致性哈希的 balancer 不会导致 clone 开销大，因为这是在 Arc 里面的。
另外，这个应该和 callopt 没关系？一致性哈希的实现应该是用不到 callopt 的才对。

**Comment by my-vegetable-has-exploded** [comment]
目前编写了比较[初步的实现](https://github.com/my-vegetable-has-exploded/volo/commit/3b67d27265010a6e0171ed08742c73475291de80), 目前主要困难还是在hash code的获取上（一直没搞定😭，上面实现还是基于硬编码hash code的方式）。
我觉得使用KeyFunc确实比较好，但是rust中没有像golang中那样可以通过interface{}方便下转，我尝试在LoadBalancetrait中get_picker中添加cx和req，
```rust
    fn get_picker<'future, 'cx>(
        &'future self,
        endpoint: &'future Endpoint,
        discover: &'future D,
		cx: &'cx Cx,
		req:  Req,
	)  -> Self::GetFut<'future>
    where
        Self: 'future;
```
会导致很多地方需要加上cx和req的泛型类型，更重要的是context在volo-grpc和volo-thrift实现不同，而且对用户而言这个context不是可见的，如果要去使用泛型的方式去定义option的KeyFunc(context, req)的话用户没办法得到这个context类型来定义KeyFunc。
如果使用impl这种对象形式的话（和trait中的大量泛型放在一起多少别扭），req的约束比较少
```rust
    Req: Clone + Send + Sync + 'static,
```
通过any trait倒可以实现下转，但是像volo-thrift会对req包装成ThriftMessage，这个类型用户自定义KeyFunc的时候也是不知道的。
这部分要麻烦你们看看怎么搞，感谢

**Comment by driventokill** [comment]
> 会导致很多地方需要加上cx和req的泛型类型，更重要的是context在volo-grpc和volo-thrift实现不同，而且对用户而言这个context不是可见的，如果要去使用泛型的方式去定义option的KeyFunc(context, req)的话用户没办法得到这个context类型来定义KeyFunc。

https://github.com/cloudwego/volo/blob/12319992496acfc42e1fd2312d22e235912a54a2/volo/src/loadbalance/mod.rs#LL31C5-L35C31

```rust
    fn get_picker<'future>(
        &'future self,
        endpoint: &'future Endpoint,
        discover: &'future D,
    ) -> Self::GetFut<'future>
```
这里的 Endpoint 只包含了callee的信息，所以ConsistLoadBalance中就算加入KeyFunc也无法生成需要的hashcode。如果重构一下这个接口支持Context传入，只要在LoadBalanceService里面修改一下把Context传进去就可以了吧，不用关心在 volo-thrift 和 volo-grpc中的实现是否相同（只要是同一个trait就可以了），看起来也不太需要req的信息。

**Comment by ethe** [comment]
你拿不到 Req 的具体类型，所以传入也没用。但 context 可以拿到具体类型 `ThriftContext` 或 `GrpcContext`，所以 get_picker 可以传入具体的 context 类型，如果希望保持通用性，可以考虑传入 metainfo 而不是 context，计算 hash key 所需要的信息用 metainfo 传递

**Comment by my-vegetable-has-exploded** [comment]
> 你拿不到 Req 的具体类型，所以传入也没用。但 context 可以直接约束具体类型 `ThriftContext` 或 `GrpcContext`，所以 get_picker 可以传入具体的 context 类型，如果希望保持通用性，可以考虑传入 metainfo 而不是 context，计算 hash key 所需要的信息用 metainfo 传递

1、目前泛型的写法，想要加context类型参数到LoadBalance中，我试了一下，LoadBalanceService需要加PhantomData（因为mk_lb时还没有具体context内容，不能像discover一样一直传下去），而且MkLbLayer 、LbConfig、LoadBalanceLayer、LoadBalanceService都要加上这些参数。 （感觉有点怪，如果有更好的写法，能不能改个小例子给我参考一下呢？）
```rust
pub trait LoadBalance<Cx,D>:  Send + Sync + 'static
where
    Cx: 'static + Context + Send + Sync,
    D: Discover,

#[derive(Clone)]
pub struct LoadBalanceService<Cx, D, LB, S>
where
    Cx: 'static + Context + Send + Sync,
    D: Discover,
    LB: LoadBalance<Cx, D>,
{
    discover: D,
    load_balance: Arc<LB>,
    service: S,
    retry: usize,
    cx: PhantomData<Cx>,
}
```
2、 关于是否需要req， 我觉得hash key可以使用除了caller的address这类context信息外， 是否存在用户使用资源路径这些request相关信息的场景呢（我不太了解）。 如果req信息也是需要的，用户将信息中部分信息clone再传递进context或者metainfo中似乎丢失了KeyFunc这种优势。 而且让用户去使用context（原本是屏蔽掉的）、metainfo（原先不需要使用）感觉反而加重用户负担（因为这里面context不像go中那种统一且使用方式对大家都很熟悉。）。 这些导致我目前偏向通过用户直接将计算得到的hash code通过callopt中caller_tags传递到loadbalance中。

**Comment by my-vegetable-has-exploded** [comment]
我想了想，我觉得context大部分内容对于loadbalance来说都没有意义（像很多timeout、编码的设置），感觉传递extensions或者caller进来通过typemap去获取感觉也是一个可以接受的方式（实现也比较简单）。
我尝试写了两个版本[通过extension和key_func](https://github.com/cloudwego/volo/compare/main...my-vegetable-has-exploded:volo:consisthash-extension)以及[用户直接设置request_code](https://github.com/cloudwego/volo/compare/main...my-vegetable-has-exploded:volo:consisthash)。 可以看看哪个好一些，然后我提个pr继续完善一下😂。
（不过个人在这个实现限制下还是偏向直接request_code的，因为使用定义key_func时context等并不是直接对用户可见、req也不能直接得到（导致没办法直接复用cx、req），相当于还是需要用户去设置需要传递的内容，使用上差别不大，感觉算好后直接使用request_code传递过去还能免去一些clone开销）

**Comment by ethe** [comment]
extension 和 metainfo 哪个更推荐呢？cc @PureWhiteWu

**Comment by PureWhiteWu** [comment]
太赞了，两种方式都实现了。
我刚仔细看了一下，其实我更倾向于使用第一种方式，也就是 extension 和 key_func 来做。
request_code 最大的问题是，这是个 callopt 但是只有 consistent lb 用到了，在非 consistent lb 下这个接口的存在就会非常奇怪。
另外，我觉得既然都传递了，不如就传递 context 吧，万一用户需要根据 endpoint 去拿一些信息呢，咱们尽可能提供足够的信息和可扩展性。
Req 的话，我想了一下，直接拿 &ThriftMessage<UserRequest> 感觉也是可行的？只要我们给个 example 说清楚这里的类型，应该用户使用上不会有问题？

**Comment by my-vegetable-has-exploded** [comment]
> request_code 最大的问题是，这是个 callopt 但是只有 consistent lb 用到了，在非 consistent lb 下这个接口的存在就会非常奇怪。

request_code接口可以和key_func一样，其实本质就是就是typemap（位于extensions或者caller_tags中）中加了RequestCode结构，然后让ConsistentHashBalance从typemap里面读。
```rust
pub struct RequestCode(pub u64);

impl CallOpt {
    /// Creates a new [`CallOpt`].
    pub fn set_request_code(&mut self, code: u64) -> &mut Self {
        self.extensions.insert(RequestCode(code));
        self
    }
}
```
> 另外，我觉得既然都传递了，不如就传递 context 吧，万一用户需要根据 endpoint 去拿一些信息呢，咱们尽可能提供足够的信息和可扩展性。

感觉使用caller会比extensions好一点？ 主要是context在grpc和thrift中类型不同，一方面用户去使用可能去了解一下内部知识（感觉对用户比较麻烦），最主要是要在loadbalance中传递context需要特化，对于我来说有些困难😭（涉及到地方有些不熟悉也不怎么敢，如果要实现得麻烦你们在此再修）。
> context 类型可以特化，代价是 Load Balance service 不再协议无关


> Req 的话，我想了一下，直接拿 &ThriftMessage 感觉也是可行的？只要我们给个 example 说清楚这里的类型，应该用户使用上不会有问题？

除了ThriftMessage外，不过req的具体类型并不确定，一个service中多个method的req类型不一致，get_picker如果要用这个req类型loadbalance这个trait没有办法实例化（使用any trait应该也能做，但是放在一堆泛型实现的感觉不太搭😂）。

麻烦了

@PureWhiteWu @ethe

**Comment by PureWhiteWu** [comment]
> 除了ThriftMessage外，不过req的具体类型并不确定，一个service中多个method的req类型不一致，get_picker如果要用这个req类型loadbalance这个trait没有办法实例化（使用any trait应该也能做，但是放在一堆泛型实现的感觉不太搭😂）。

确实，感觉这样的易用性还不如直接让用户传递一个 hash 过来。

我刚想了一下，第一种方式（extension/callee）+ keyfunc 也存在问题，用户在发起 RPC 调用的时候 RpcInfo 还没被构造出来，所以这时候是没有 extension 存在的，用户也没法把对应的 hash 值塞进去。

第二种方式的问题就是我之前说的，必须在 CallOpt 上开接口，如果没用到 consist lb 的情况下这个接口的存在就比较冗余和迷惑。

看来唯一可行且用户体验较好的方案就是直接用 metainfo 传递一个 hash code 进来了？ cc @ethe @LYF1999 觉得呢？

**Comment by my-vegetable-has-exploded** [comment]
> 我刚想了一下，第一种方式（extension/callee）+ keyfunc 也存在问题，用户在发起 RPC 调用的时候 RpcInfo 还没被构造出来，所以这时候是没有 extension 存在的，用户也没法把对应的 hash 值塞进去。
> 
> 第二种方式的问题就是我之前说的，必须在 CallOpt 上开接口，如果没用到 consist lb 的情况下这个接口的存在就比较冗余和迷惑。

传hash code的做法，我写的example里面，主要过程是这样的用户通过callopt进行set_request_code、call时会对mk_cx后得到的context进行apply callopt把callopt内容添加到context中， get_picker从extensions/caller_tags中去获取。
```rust
pub struct RequestCode(pub u64);

impl CallOpt {
    pub fn set_request_code(&mut self, code: u64) -> &mut Self {
        self.extensions.insert(RequestCode(code));
        self
    }
}

impl volo::client::Apply<crate::context::ClientContext> for CallOpt {
    fn apply(self, cx: &mut crate::context::ClientContext) -> Result<(), Self::Error> {
        .....
        cx.extensions_mut().extend(self.extensions.0);
        Ok(())
    }
}

    fn get_picker<'future>(
        &'future self,
        extensions: &'future Extensions,  // extensions换成caller, 然后用caller的caller_tags是不是更合适一点？
        endpoint: &'future Endpoint,
        discover: &'future D,
    ) -> Self::GetFut<'future>
    where
        Self: 'future,
    {
        async move {
              let request_key = extensions.get::<RequestCode>(); // 仅仅对于consisthash balancer
        }
    }
```
根据我写的example 跑的情况，感觉传递是行得通的😂（不知道是不是有情况没有考虑到）

**Comment by ethe** [comment]
我觉得可以走 `metainfo`，这样现有接口不需要任何变更

**Comment by PureWhiteWu** [comment]
> 传hash code的做法，我写的example里面，主要过程是这样的用户通过callopt进行set_request_code、call时会对mk_cx后得到的context进行apply callopt把callopt内容添加到context中， get_picker从extensions/caller_tags中去获取。

对，这个的问题就是需要新增一个 set_request_code 的接口，然后这个接口还是只有 consist lb 才会用到的，所以会很奇怪。

**Comment by my-vegetable-has-exploded** [comment]
> 对，这个的问题就是需要新增一个 set_request_code 的接口，然后这个接口还是只有 consist lb 才会用到的，所以会很奇怪。

大概明白意思了， 不过我还是有点不理解，那像caller_tags这些typemap主要用来传递什么呢？ 😂

**Comment by my-vegetable-has-exploded** [comment]
> 这些 typemap 主要是为了服务发现和治理预留的扩展，比如如果有个服务发现策略需要根据比如 集群、idc、zone 这些进行调度的话，就可以放在 typemap 里面。

明白了， 感谢
