### ISSUE TITLE
代码生成多个文件和生成http-gw代码

### ISSUE THREAD

**Issue by moonfdd** [cloudwego/volo#78]
1.代码生成，能不能不生成一个文件啊？想生成多个文件，因为proto想作为集中仓库，全部生成到一个文件里，不现实。proto是按文件夹管理的，我想生成的代码也是同样的文件夹。现在的问题是rs文件里不仅包含了path的代码，还包含了includes的代码，这没法分开生成了。
2.能生成http代码吗？protoc-gen-grpc-gateway这个就能生成go的http的代码。

**Comment by moonfdd** [comment]
![image](https://user-images.githubusercontent.com/66774304/199199657-3abdc151-7ae3-4d42-aa6d-1eec59c9c798.png)

**Comment by moonfdd** [comment]
![image](https://user-images.githubusercontent.com/66774304/199200114-d8b0bd61-7962-431b-9b8e-94db772c0ff2.png)

**Comment by moonfdd** [comment]
![1667294122206](https://user-images.githubusercontent.com/66774304/199200887-a24ee5d7-064b-40e7-a897-e3bc7133f8d5.jpg)

**Comment by PureWhiteWu** [comment]
1. 关于这个问题，我觉得首要的是不要以 Go 的思维来思考 Rust。我们在 Go 中也有相关的实践，是将所有代码生成到一个统一的仓库进行管理（比如 cloudwego/kitex 有一些业务就这么做），那是因为 Go 没有提供足够强大的编译时能力，不能在编译时生成所需 idl，而且受限于 Go 的性能如果 idl 较多的情况下，parse + generate 的耗时会很长，所以一般都是开发之前提前生成好。
但是 Rust 中得益于 Rust 强大的性能和编译时能力，以上这些都不是问题，所以在整个 Rust 社区中，一般都采用在编译时直接生成所需生成代码的实践（tonic 也是如此）。
回到你的原始的问题，我们目前支持在 volo.yml 中通过不同的 entry 来生成不同的文件，但是如你所述，因为 includes 也会一起被生成，所以其实无法作为集中仓库进行管理和使用，我们也不推荐在 Rust 中采用生成代码集中仓库的实践。
你可以先尝试一下直接在编译时生成，只对 idl 仓库进行版本管理，看下是否有无法解决的问题，如果有的话欢迎再提出～
2. 目前不支持，如果你有明确需求场景并且可以在生产环境落地的话可以联系我们可以看下如何支持；如果你有意愿来实现的话更好啦，可以单独提一个 issue 来认领一下并说明一下你的实现方案～

**Comment by moonfdd** [comment]
@PureWhiteWu 
1.那我这边就不在集中仓库里生成代码了。entry里的path用includes的proto，includes是全部生成了，能不能改成按需生成？（1）比如includes的service就不用生成代码了。（2）假设includes里有10个message，path里用到了includes里的4个message，那么includes里只需要生成4个message的代码。这样能去掉很多无用的代码。
2.我现在的公司和上家公司都是开发http+grpc的服务，http包裹grpc，生产环境肯定要用到。go中用的是protoc-gen-grpc-gateway生成代码。tonic中有tonic-web，但是tonic-web不好用，postman测试无效，所以我才放弃了tonic。

**Comment by PureWhiteWu** [comment]
1. 我们 Thrift 已经实现了剪枝，Protobuf 还没支持上，我们复用一下 Thrift 的实现就行了，这个我之后建一个新的 issue；
2. 如果你这边公司有意愿使用 Volo 并且能落地的话可以填一下这个表格 https://wenjuan.feishu.cn/m/cfm?t=sH0dv11ZVGDi-5kda，我们会优先开发这个功能。

**Comment by moonfdd** [comment]
@PureWhiteWu 
2.表格填写了

**Comment by PureWhiteWu** [comment]
好的，我们之后会有专门的运营同学来联系你，看看如何更好的提供支持～
这个 issue 我先关闭啦，如果还有其他问题随时回复或者新开 issue～
