### ISSUE TITLE
Incorrect error propagation from server to client

### ISSUE THREAD

**Issue by tonyvelichko** [cloudwego/volo#83]
## Bug Report

Current behavior with error propagation leads to client error loss. 
The issue is the same as in [spring-cloud-gateway](https://github.com/spring-cloud/spring-cloud-gateway/issues/2679)

### Description

I've tried to compare the results from the official GRPC server and the Volo. You can create two identical implementations for Java/Scala/Kotlin and Volo which just respond with an error status for the unary call. 

The Java version responds with a single error message and closes the stream in this message as well, as a result, the client receives an error as a result of the call. 

The Volo version responds with two messages first with an error, and second with a stream close, as a result, the client is stuck.

**Comment by PureWhiteWu** [comment]
Thanks for your feedback! We will investigate this.
Is this behaviour documented in the grpc spec? Could you please help me to point it out?(I searched the [grpc http2 protocol spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) but didn't find relative information.) Or is this a de facto standard?

**Comment by tonyvelichko** [comment]
I couldn't find any documentation for that either and seems that behavior is coming from the official (grpc-java) client implementation. 

I've tried several clients [that build upon grpc-java]
- `https://github.com/typelevel/fs2-grpc` reacted as INTERNAL error (instead of what was sent from the server)
- `https://github.com/salesforce/reactive-grpc` stuck without any of errors
- `https://github.com/grpc/grpc-java` reacted as INTERNAL error 

Reacted as having no response and ignored everything that come earlier in that stream.

**Comment by PureWhiteWu** [comment]
Thank you for the further information!
Seems like that is undefined behavior, we will take a look at `tonic` and `grpc-go` implementation and discuss if we will change this.

**Comment by Millione** [comment]
> Response-Headers & Trailers-Only are each delivered in a single HTTP2 HEADERS frame block. Most responses are expected to have both headers and trailers but Trailers-Only is permitted for calls that produce an immediate error. Status must be sent in Trailers even if the status code is OK.

@tonyvelichko It seems like grpc-java/grpc-go client doesn't handle `both headers and trailers` situation rightly. However, now problem solved.
