### ISSUE TITLE
Proposal: shall we use `async_fn_in_traits`?

### ISSUE THREAD

**Issue by PureWhiteWu** [cloudwego/volo#89]
Now that `async_fn_in_traits` has reached MVP in nightly, and will hopefully be stabilized in six months.

Shall we use that?

FYI:
1. https://blog.rust-lang.org/inside-rust/2022/11/17/async-fn-in-trait-nightly.html
2. https://github.com/rust-lang/rust/issues/91611

**Comment by PureWhiteWu** [comment]
I've tried this, but seems we have encountered the `Send` bound problem in volo.

I will try again some time later when this feature is more mature.

**Comment by my-vegetable-has-exploded** [comment]
After using async_fn_in_traits, will we be able to provide msrv?

**Comment by PureWhiteWu** [comment]
@my-vegetable-has-exploded Yes, this will be a breaking change, we are discussing and testing the new design.
Long story short, we are going to change `Service` to something like this:
```rust
pub trait Service<Cx, Request> {
 /// Responses given by the service.
 type Response;
 /// Errors produced by the service.
 type Error;
 /// Process the request and return the response asynchronously.
 fn call<'cx, 's>(&'s self, cx: &'cx mut Cx, req: Request) -> impl Future<Output = Result<Self::Response, Self::Error>> + Send + 'cx
 where
 's: 'cx;
}
```

But we are not quite sure if this works fine, so we need some more tests.

**Comment by PureWhiteWu** [comment]
We met this issue https://github.com/rust-lang/rust/issues/100013 when migrating to rpitit, maybe we need to wait for this bug to be fixed.
